CREATE TABLE IF NOT EXISTS tags (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE,
  color TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tags_created_at
ON tags (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tags_name
ON tags (name);

CREATE INDEX IF NOT EXISTS idx_tags_color
ON tags (color);
