const SKILL_KEYWORDS: [&str; 57] = [
    "typescript",
    "javascript",
    "vue",
    "nuxt",
    "react",
    "angular",
    "svelte",
    "node",
    "deno",
    "tauri",
    "rust",
    "python",
    "java",
    "c#",
    "go",
    "kotlin",
    "swift",
    "php",
    "sql",
    "postgresql",
    "mysql",
    "sqlite",
    "mongodb",
    "redis",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "github actions",
    "gitlab ci",
    "aws",
    "azure",
    "gcp",
    "linux",
    "graphql",
    "rest",
    "microservices",
    "grpc",
    "oauth",
    "jwt",
    "vite",
    "vitest",
    "jest",
    "playwright",
    "cypress",
    "selenium",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "nlp",
    "llm",
    "prompt engineering",
    "figma",
    "agile",
];

pub fn detect_skills(text: &str) -> Vec<String> {
    let text_lc = text.to_ascii_lowercase();

    SKILL_KEYWORDS
        .iter()
        .filter(|skill| text_lc.contains(**skill))
        .map(|skill| skill.to_string())
        .collect()
}
