export const defaultSkillOptions = [
  "Communication",
  "Customer Service",
  "Data Analysis",
  "Docker",
  "Excel",
  "Figma",
  "Git",
  "JavaScript",
  "Leadership",
  "Node.js",
  "Project Management",
  "Python",
  "SQL",
  "TypeScript",
  "Vue",
] as const;
